version: '3.8'

services:
  # --- 1. Web Sunucusu ---
  website:
    build: .
    container_name: asec_website
    ports:
      - "8083:80"
    volumes:
      - ./src:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - IS_DOCKER=true
      - TZ=Europe/Istanbul
    depends_on:
      - database

  # --- 2. Veritabanı ---
  # PHP Config dosyasında 'DB_SERVER' olarak bu servisin adı olan 'database' kullanılmalı.
  database:
    image: mysql:8.0
    container_name: asec_mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root  # PHP Config dosyasında DB_PASSWORD 'root' olmalı
      MYSQL_DATABASE: db_asec
      TZ: Europe/Istanbul
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  # --- 3. Yönetim Paneli ---
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: asec_pma
    ports:
      - "45081:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - database

volumes:
  db_data: