version: '3.8'

services:
  # --- 1. Web Sunucusu ---
  website:
    build: .
    # container_name: KALDIRILDI (Otomatik isimlendirilecek)
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./sessions:/tmp  # Session dosyaları burada tutulacak
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - IS_DOCKER=true
      - TZ=Europe/Istanbul
    depends_on:
      - database

  # --- 2. Veritabanı ---
  database:
    image: mysql:8.0
    # container_name: KALDIRILDI
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_asec
      TZ: Europe/Istanbul
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  # --- 3. Yönetim Paneli (PhpMyAdmin) ---
  pma:
    image: phpmyadmin/phpmyadmin
    # container_name: KALDIRILDI
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - database

volumes:
  db_data: